define(['layerWidget',
        'shapeWidget',
        'brushWidget',
        'basePicWidget',
        'colorWidget',
        'fileWidget',
        'filterWidget',
        'slicerWidget'
        ],
    function (layerWidget,
              shapeWidget,
              brushWidget,
              basePicWidget,
              colorWidget,
              fileWidget,
              filterWidget,
              slicerWidget
    ) {
    return [
        {
            fnTitle:'&#xe653;图层',
            fnPanel:layerWidget.LayerWidgetPanel,
            panelData:{},
        },
        {
            fnTitle:'&#xe60d;底图',
            fnPanel:basePicWidget.BasePicWidgetPanel,
        },
        {
            fnTitle:'&#xe67f;画笔',
            fnPanel:brushWidget.BrushWidgetPanel,
        },
        {
            fnTitle:'&#xe755;切刀',
            fnPanel:slicerWidget.SlicerWidgetPanel,
        },
        {
            fnTitle:'&#xe60a;颜色',
            fnPanel:colorWidget.ColorWidgetPanel
        },
        {
            fnTitle:'&#xe6ff;形状',
            fnPanel:shapeWidget.ShapeWidgetPanel
        },
        {
            fnTitle:'&#xe794;滤镜',
            fnPanel:filterWidget.FilterWidgetPanel
        },
        {
            fnTitle:'&#xe640;文件',
            fnPanel:fileWidget.FileWidgetPanel
        }
    ]
})